#every yml starts with version
version: 2

sources:
  - name: staging
    database: praxis-wall-411617
    schema:
      week4_dataset

      # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_2019

      
